Make sure loglevel is used in all cloudflared commands

diff --git a/Dockerfile.entrypoint b/Dockerfile.entrypoint
--- a/Dockerfile.entrypoint
+++ b/Dockerfile.entrypoint
@@ -2,14 +2,15 @@
 set -eo pipefail
 
 if [ "$1" = "cloudflared" ] && [ "$2" = "tunnel" ]; then
+
     # Prevent message about missing config file.
     echo "---" > /etc/cloudflared/config.yml
 
     # Never auto update in docker containers.
-    export NO_AUTOUPDATE=true
+    export NO_AUTOUPDATE='true'
 
     if [ -n "${TUNNEL_NAME}" ]; then
-        >&2 echo "You cannot use TUNNEL_NAME with firecow/cloudflared image, its auto generated" && exit 1
+        >&2 echo "You cannot use TUNNEL_NAME or --name with firecow/cloudflared image, its auto generated" && exit 1
     fi
 
     if [ -n "${TUNNEL_FORCE_PROVISIONING_DNS}" ]; then
@@ -26,30 +27,35 @@ if [ "$1" = "cloudflared" ] && [ "$2" = "tunnel" ]; then
 
     if [ -z "${TUNNEL_TRANSPORT_LOGLEVEL}" ]; then
         export TUNNEL_TRANSPORT_LOGLEVEL=warn
-        echo "TUNNEL_TRANSPORT_LOGLEVEL defaulting to 'warn'"
     fi
 
     if [ -z "${TUNNEL_LOGLEVEL}" ]; then
         export TUNNEL_LOGLEVEL=warn
-        echo "TUNNEL_LOGLEVEL defaulting to 'warn'"
     fi
 
+    # function that prints info message, if TUNNEL_LOG_LEVEL is DEBUG or INFO
+    function printInfo {
+      if [ ${TUNNEL_LOGLEVEL,,} != 'info' ] && [ ${TUNNEL_LOGLEVEL,,} != 'debug' ]; then return 0; fi
+      echo "${1}"
+    }
+
+    export TUNNEL_FORCE_PROVISIONING_DNS='false'
     export TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME/https:\/\//}
     export TUNNEL_NAME=${TUNNEL_NAME:-$TUNNEL_HOSTNAME}
 
     EXISTING_TUNNELS_JSON=$(cloudflared tunnel list --name "${TUNNEL_NAME}" --output json)
     if [ "${EXISTING_TUNNELS_JSON}" != "[]" ]; then
-        echo "Deleting existing tunnel '${TUNNEL_NAME}'"
-        cloudflared tunnel --loglevel warn delete "${TUNNEL_NAME}"
+        printInfo "Deleting existing tunnel '${TUNNEL_NAME}'"
+        cloudflared tunnel delete "${TUNNEL_NAME}"
     else
-        echo "No existing tunnel found"
+        printInfo "No existing tunnel found"
     fi
-    echo "Creating new tunnel '${TUNNEL_NAME}'"
-    cloudflared tunnel --loglevel warn create "${TUNNEL_NAME}" 1> /dev/null
-    echo "Creating CNAME from '${TUNNEL_HOSTNAME}' to tunnel named '${TUNNEL_NAME}'"
-    cloudflared tunnel --loglevel warn route dns --overwrite-dns "${TUNNEL_NAME}" "${TUNNEL_HOSTNAME}"
+    printInfo "Creating new tunnel '${TUNNEL_NAME}'"
+    cloudflared tunnel create "${TUNNEL_NAME}" 1> /dev/null
+    printInfo "Creating CNAME from '${TUNNEL_HOSTNAME}' to tunnel named '${TUNNEL_NAME}'"
+    cloudflared tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "${TUNNEL_HOSTNAME}"
     unset TUNNEL_HOSTNAME
-    echo "Tunnels are now active."
+    printInfo "Tunnels are now active."
     exec "cloudflared" "tunnel"
 else
     exec "$@"
