Greatly reduce entrypoint complexity and bump to 2022.3.4

diff --git a/Dockerfile.entrypoint b/Dockerfile.entrypoint
--- a/Dockerfile.entrypoint
+++ b/Dockerfile.entrypoint
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
 set -e
 
@@ -53,36 +53,20 @@ if [ ! -f /etc/cloudflared/config.yml ]; then
 fi
 
 derived_tunnel_name=$(echo "${TUNNEL_HOSTNAME}" | sed "s,^.*://,,g" | tr '[:upper:]' '[:lower:]')
-export TUNNEL_NAME="${TUNNEL_NAME:-${derived_tunnel_name}}"
-
-# Check for active connections and/or cleanup pending connections
-set +e
-tunnel_info=$(cloudflared --loglevel error tunnel info --output json "${TUNNEL_NAME}" 2> /dev/null)
-set -e
-is_active=$(echo "${tunnel_info}" | jq '.conns[] | .conns[] | select(.is_pending_reconnect == false) | length' | wc -l)
-if [ "$is_active" != "0" ]; then
-  printAndExit 1 "Active tunnels for '${TUNNEL_NAME}' found, shutting down"
-fi
-is_pending=$(echo "${tunnel_info}" | jq '.conns[] | .conns[] | select(.is_pending_reconnect == true) | length' | wc -l)
-if [ "$is_pending" != "0" ]; then
-  printError "Cleaning pending connections for '${TUNNEL_NAME}'"
-  cloudflared --loglevel 'error' tunnel cleanup "${TUNNEL_NAME}"
-fi
-
-existing_tunnels_json=$(cloudflared --loglevel 'error' tunnel list --name "${TUNNEL_NAME}" --output json)
-if [ "${existing_tunnels_json}" != "[]" ]; then
-  printInfo "Deleting existing named tunnel '${TUNNEL_NAME}'"
-  cloudflared --loglevel 'error' tunnel delete "${TUNNEL_NAME}"
-else
-  printInfo "No existing named tunnel found"
-fi
-
-printInfo "Creating new named tunnel '${TUNNEL_NAME}'"
-cloudflared --loglevel 'error' tunnel create "${TUNNEL_NAME}" 1>/dev/null
-
-printInfo "Routing dns from '${TUNNEL_NAME}' to tunnel"
-cloudflared --loglevel 'error' tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "${derived_tunnel_name}"
-
 unset TUNNEL_HOSTNAME
+
+cloudflared --loglevel 'error' tunnel token "${derived_tunnel_name}" > /tmp/creds.json || exit_code=$?
+if [ -z "${exit_code}" ]; then
+  tunnel_id=$(base64 -d < /tmp/creds.json | jq -r '.t')
+  base64 -d < /tmp/creds.json | jq '.["AccountTag"] = .a | .["TunnelID"] = .t | .["TunnelSecret"] = .s' > /etc/cloudflared/"${tunnel_id}".json
+fi
+
+if [ -n "${exit_code}" ]; then
+  printInfo "Creating new named tunnel '${derived_tunnel_name}'"
+  cloudflared --loglevel 'error' tunnel create "${derived_tunnel_name}" 1>/dev/null
+
+  printInfo "Routing dns from '${derived_tunnel_name}' to tunnel"
+  cloudflared --loglevel 'error' tunnel route dns --overwrite-dns "${derived_tunnel_name}" "${derived_tunnel_name}"
+fi
 
 exec "cloudflared" "tunnel" "run" "${derived_tunnel_name}"
