Entrypoint refactor (#22)

diff --git a/Dockerfile.entrypoint b/Dockerfile.entrypoint
--- a/Dockerfile.entrypoint
+++ b/Dockerfile.entrypoint
@@ -1,57 +1,65 @@
-#!/bin/bash
-set -eo pipefail
+#!/bin/sh
 
-if [ "$1" = "cloudflared" ] && [ "$2" = "tunnel" ]; then
+set -e
 
-    # Prevent message about missing config file.
-    echo "---" > /etc/cloudflared/config.yml
+# function that prints info message, if TUNNEL_LOGLEVEL is DEBUG or INFO
+printInfo() {
+  tunnel_loglevel=${TUNNEL_LOGLEVEL}
+  if [ "${tunnel_loglevel}" != 'info' ] && [ "${tunnel_loglevel}" != 'debug' ]; then return 0; fi
+  echo "${1}"
+}
 
-    if [ -n "${TUNNEL_NAME}" ]; then
-        >&2 echo "You cannot use TUNNEL_NAME or --name with firecow/cloudflared image, its auto generated" && exit 1
-    fi
-
-    if [ -n "${TUNNEL_FORCE_PROVISIONING_DNS}" ]; then
-        >&2 echo "You cannot use TUNNEL_FORCE_PROVISIONING_DNS with firecow/cloudflared image, its determined via route dns command" && exit 1
-    fi
-
-    if [ -z "${TUNNEL_HOSTNAME}" ]; then
-        >&2 echo "You need to specify TUNNEL_HOSTNAME" && exit 1
-    fi
-
-    if [ -z "${TUNNEL_URL}" ]; then
-        >&2 echo "You need to specify TUNNEL_URL" && exit 1
-    fi
-
-    if [ -z "${TUNNEL_TRANSPORT_LOGLEVEL}" ]; then
-        export TUNNEL_TRANSPORT_LOGLEVEL=fatal
-    fi
-
-    if [ -z "${TUNNEL_LOGLEVEL}" ]; then
-        export TUNNEL_LOGLEVEL=fatal
-    fi
-
-    # function that prints info message, if TUNNEL_LOG_LEVEL is DEBUG or INFO
-    function printInfo {
-      if [ ${TUNNEL_LOGLEVEL,,} != 'info' ] && [ ${TUNNEL_LOGLEVEL,,} != 'debug' ]; then return 0; fi
-      echo "${1}"
-    }
-
-    export TUNNEL_FORCE_PROVISIONING_DNS='false'
-    export TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME/https:\/\//}
-    export TUNNEL_NAME=${TUNNEL_NAME:-$TUNNEL_HOSTNAME}
-
-    EXISTING_TUNNELS_JSON=$(cloudflared tunnel list --name "${TUNNEL_NAME}" --output json)
-    if [ "${EXISTING_TUNNELS_JSON}" != "[]" ]; then
-        printInfo "Deleting existing tunnel '${TUNNEL_NAME}'"
-        cloudflared tunnel delete "${TUNNEL_NAME}"
-    else
-        printInfo "No existing tunnel found"
-    fi
-    printInfo "Creating new tunnel '${TUNNEL_NAME}'"
-    cloudflared tunnel create "${TUNNEL_NAME}" 1> /dev/null
-    cloudflared tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "${TUNNEL_HOSTNAME}"
-    unset TUNNEL_HOSTNAME
-    exec "cloudflared" "tunnel"
-else
-    exec "$@"
+# Prevent message about missing config file.
+if [ ! -f /etc/cloudflared/config.yml ]; then
+  printInfo "/etc/cloudflared/config.yml not found autogenerating one"
+  echo "---" >/etc/cloudflared/config.yml
 fi
+
+if [ -n "${TUNNEL_NAME}" ]; then
+  echo >&2 "You cannot use TUNNEL_NAME it's derived from TUNNEL_HOSTNAME" && exit 1
+fi
+
+if [ -n "${TUNNEL_FORCE_PROVISIONING_DNS}" ]; then
+  echo >&2 "You cannot use TUNNEL_FORCE_PROVISIONING_DNS it's determined via route dns command" && exit 1
+fi
+
+if [ -z "${TUNNEL_HOSTNAME}" ]; then
+  echo >&2 "You need to specify TUNNEL_HOSTNAME" && exit 1
+fi
+
+if [ -z "${TUNNEL_URL}" ] && [ -z "${TUNNEL_UNIX_SOCKET}" ]; then
+  echo >&2 "You need to specify TUNNEL_URL or TUNNEL_UNIX_SOCKET" && exit 1
+fi
+
+if [ -z "${TUNNEL_TRANSPORT_LOGLEVEL}" ]; then
+  printInfo "TUNNEL_TRANSPORT_LOGLEVEL defaulting to error"
+  export TUNNEL_TRANSPORT_LOGLEVEL=error
+fi
+
+if [ -z "${TUNNEL_LOGLEVEL}" ]; then
+  printInfo "TUNNEL_LOGLEVEL defaulting to error"
+  export TUNNEL_LOGLEVEL=error
+fi
+
+printInfo "NO_AUTOUPDATE defaulting to true"
+export NO_AUTOUPDATE="true"
+
+export TUNNEL_FORCE_PROVISIONING_DNS='false'
+derived_tunnel_name=$(echo "$TUNNEL_HOSTNAME" | sed "s/https:\/\///g")
+
+export TUNNEL_NAME="${TUNNEL_NAME:-$derived_tunnel_name}"
+
+existing_tunnels_json=$(cloudflared --loglevel 'error' tunnel list --name "${TUNNEL_NAME}" --output json)
+if [ "${existing_tunnels_json}" != "[]" ]; then
+  printInfo "Deleting existing named tunnel '${TUNNEL_NAME}'"
+  cloudflared --loglevel 'error' tunnel delete "${TUNNEL_NAME}"
+else
+  printInfo "No existing named tunnel found"
+fi
+printInfo "Creating new named tunnel '${TUNNEL_NAME}'"
+cloudflared --loglevel 'error' tunnel create "${TUNNEL_NAME}" 1>/dev/null
+printInfo "Routing dns '${TUNNEL_HOSTNAME}' to tunnel '${TUNNEL_NAME}'"
+cloudflared --loglevel 'error' tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "${derived_tunnel_name}"
+unset TUNNEL_HOSTNAME
+
+exec "$@"
